GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "noLikes3",
    "author": "authortest3", 
    "url": "fakeurl.conm/blog2"
}


###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "TestingNewBlog",
    "password": "realpassword",
    "name": "Tester"
}

###

GET http://localhost:3001/api/users